### ISSUE TITLE
Mis päeval teha üritus?

### ISSUE THREAD

**Issue by martinpaljak** [alvatal/sfd-2015#1]
Vaba tarkvara päev on 19.09.2015 (laupäev). Korraldusmeeskonnale ehk lihtsam, samas nädala sees liigub rohkem inimesi?

**Comment by boamaod** [comment]
Ma küsiks seda nii, et millal viitsivad inimesi kollitavad aktivistid ise kohale ronida, sh mis on nende boonus kohale ronimisest (mingi õhtune järelüritus, kuhu edasi minna, või mingi eelüritus stiilis väike häkaton vms, kust koos tulla --- või mõlemad)? Teiseks seda, et mis tagab suurema/huvitavama meediakajastuse (mis tüüpi kajastust me tahame, rõõmus reportaaž mõnda päevalehte, 1 min uudistes, mingi pikem videolugu kuskil teles või portaalis, põhjalikum lugu eeldaks vist mingit seotust mõne laiema probleemiga)? Reedel töölt tulevaid inimesi vist väga lihtsalt rajalt maha ei võta või vahet pole? Kas samal ajal mingit laada tüüpi vms rahvaüritust pole, mille n-ö väravasse kollitama minna?

**Comment by martinpaljak** [comment]
Ajaliselt kujutaks ette ca 4..6h (14.00 - 19.00 ? üles sättimine tunnike ja kokku pakkimine teine tunnike), mille sisse jääks tööpäeval "töölt tuleku aeg" kui ka tavaline linnaelu aeg. Eesmärk oleks awareness building (mis see maakeelne tõlge oleks?) ja seega igasugune (loe: maksimaalne) positiivne meediakajastus hea? Samas nädalavahetuse päeval on surve meediale raudselt väiksem kui tööpäevadel

**Comment by edmundlaugasson** [comment]
"Awareness building" on "teadlikkuse tõstmine" ja selle kohta lausa [eraldi programm ja vastavad koolitused olemas RIA-s](https://www.ria.ee/itt/).

**Comment by martinpaljak** [comment]
Praeguse seisuga läheb LV ürituse korralduse jaoks laupäev 19.09.2015 12.00 Vabaduse plats.
