### ISSUE TITLE
Kus teha üritus

### ISSUE THREAD

**Issue by martinpaljak** [alvatal/sfd-2015#2]
Vabaduse väljak sobiks nime järgi eriti hästi (ja kindlasti nädalavahetusel), samas Tammsaare pargis käiks läbi rohkem ja erinevaid inimesi? Mida põlised pealinlased arvavad?

**Comment by boamaod** [comment]
Kas samal ajal on mingeid muid üritusi sealsamas või ümber? See võib kohalolevaid rahvahulki ja nende valmisolekut huvi tunda, sh meie võimalusi välja paista (ja seega meedias figureerida) oluliselt mõjutada.

**Comment by martinpaljak** [comment]
Hetkel teadaolevalt mitte. Ma ei oleks puuk ja ei eeldaks ka "kogunevaid rahvahulki" pigem mass läbi käivaid inimesi. Mõeldes enda sattumistele pealinna, on VV vist koht, kus inimestel on rohkem aega - Tammsaare pargist olen ise alati ainult läbi tuhisenud, punktist A punkti B liikudes.

**Comment by edmundlaugasson** [comment]
Siis oleks hea ka see [sõnum sõnastada](5), mida selle lühikese läbikäiguaja jooksul edastada.

**Comment by martinpaljak** [comment]
https://www.google.ee/maps/place/59%C2%B026'01.3%22N+24%C2%B044'36.3%22E/@59.433704,24.743417,398m/data=!3m1!1e3!4m2!3m1!1s0x0:0x0?hl=en  pakutakse LV poolt (kui peaks olema ülejäänud platsil mõni suurem üritus). Samas soovitatakse ka Tammsaare parki. Jääb hetkel pakutud asukoha juurde.

**Comment by martinpaljak** [comment]
Ja see koht on ka AKIS-e ürituses fikseeritud, aega seda muuta enam pole.
